### ISSUE TITLE
[Win10] Globed Causes Crash During Game Close

### ISSUE THREAD

**Issue by Brittank88** [GlobedGD/globed2#235] opened 2024-09-24 08:40 UTC
When closing the game, it will crash (after the window is already closed) if Globed is installed. Unfortunately, this produces no crash log, so I'm not sure what extra information to provide.

**Comment by dankmeme01** [comment] 2024-09-24 08:46
could you please send the regular logs from the session where that happens? located in `geode/logs/` directory

**Comment by Brittank88** [comment] 2024-09-25 09:25
[Geode 2024-09-25 19.24.20.log](https://github.com/user-attachments/files/17128577/Geode.2024-09-25.19.24.20.log)

Note: Whilst here it'll show I have a lot of installed mods, I've tested this with basically none and it still happens.

**Comment by dankmeme01** [comment] 2024-09-25 10:14
The log looks fine, so not sure what the issue is

Does it still not produce a crashlog if you enable BetterCrashlogs? (make sure to check for new files in the crashlogs directory, sometimes it can save a crashlog without showing the UI)

**Comment by Brittank88** [comment] 2024-09-25 23:49
I had BetterCrashlogs enabled, in both cases there is no log produced.

**Comment by dankmeme01** [comment] 2024-09-26 07:48
Sure, that would be great, it's really difficult to figure out the cause without a stacktrace and without being able to reproduce the issue myself.

My discord is `@dank_meme01`

**Comment by dankmeme01** [comment] 2024-11-22 10:53
was fixed in v1.7.0!

**Closed by dankmeme01** 2024-11-22 10:53 UTC
